<?php
/**
 * Export Database to SQL File
 * Export database ujian ke file SQL
 */

require_once __DIR__ . '/config/config.php';
require_once __DIR__ . '/config/database.php';

echo "========================================\n";
echo "  EXPORT DATABASE TO SQL\n";
echo "========================================\n\n";

$output_file = __DIR__ . '/database_ujian_' . date('Y-m-d_His') . '.sql';
$mysql_path = 'C:\\xampp\\mysql\\bin\\mysqldump.exe';

// Check if mysqldump exists
if (!file_exists($mysql_path)) {
    // Try alternative paths
    $mysql_path = 'mysqldump';
}

$command = sprintf(
    '"%s" --user=%s --password=%s --host=%s --single-transaction --routines --triggers %s > "%s"',
    $mysql_path,
    escapeshellarg(DB_USER),
    escapeshellarg(DB_PASS),
    escapeshellarg(DB_HOST),
    escapeshellarg(DB_NAME),
    escapeshellarg($output_file)
);

echo "Exporting database: " . DB_NAME . "\n";
echo "Output file: " . $output_file . "\n\n";

// Execute command
exec($command . ' 2>&1', $output, $return_var);

if ($return_var === 0 && file_exists($output_file) && filesize($output_file) > 0) {
    $file_size = filesize($output_file);
    echo "✅ Database exported successfully!\n";
    echo "File: " . basename($output_file) . "\n";
    echo "Size: " . number_format($file_size / 1024, 2) . " KB\n";
    echo "\n";
    echo "File location: " . $output_file . "\n";
} else {
    echo "❌ Export failed!\n";
    if (!empty($output)) {
        echo "Error: " . implode("\n", $output) . "\n";
    }
    echo "\n";
    echo "Trying alternative method using PHP...\n\n";
    
    // Alternative: Export using PHP
    export_database_php($output_file);
}

function export_database_php($output_file) {
    global $pdo;
    
    try {
        $file = fopen($output_file, 'w');
        if (!$file) {
            throw new Exception("Cannot create file: $output_file");
        }
        
        // Write header
        fwrite($file, "-- Database Export: " . DB_NAME . "\n");
        fwrite($file, "-- Export Date: " . date('Y-m-d H:i:s') . "\n");
        fwrite($file, "-- Generated by: UJAN System\n\n");
        fwrite($file, "SET SQL_MODE = \"NO_AUTO_VALUE_ON_ZERO\";\n");
        fwrite($file, "SET AUTOCOMMIT = 0;\n");
        fwrite($file, "START TRANSACTION;\n");
        fwrite($file, "SET time_zone = \"+00:00\";\n\n");
        fwrite($file, "CREATE DATABASE IF NOT EXISTS `" . DB_NAME . "` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;\n");
        fwrite($file, "USE `" . DB_NAME . "`;\n\n");
        
        // Get all tables
        $stmt = $pdo->query("SHOW TABLES");
        $tables = $stmt->fetchAll(PDO::FETCH_COLUMN);
        
        echo "Found " . count($tables) . " tables\n";
        
        foreach ($tables as $table) {
            echo "Exporting table: $table\n";
            
            // Get table structure
            $stmt = $pdo->query("SHOW CREATE TABLE `$table`");
            $create_table = $stmt->fetch(PDO::FETCH_ASSOC);
            
            fwrite($file, "-- --------------------------------------------------------\n");
            fwrite($file, "-- Table structure for table `$table`\n");
            fwrite($file, "-- --------------------------------------------------------\n\n");
            fwrite($file, "DROP TABLE IF EXISTS `$table`;\n");
            fwrite($file, $create_table['Create Table'] . ";\n\n");
            
            // Get table data
            $stmt = $pdo->query("SELECT * FROM `$table`");
            $rows = $stmt->fetchAll(PDO::FETCH_ASSOC);
            
            if (count($rows) > 0) {
                fwrite($file, "-- Dumping data for table `$table`\n\n");
                
                $columns = array_keys($rows[0]);
                $column_list = '`' . implode('`, `', $columns) . '`';
                
                foreach ($rows as $row) {
                    $values = array();
                    foreach ($row as $value) {
                        if ($value === null) {
                            $values[] = 'NULL';
                        } else {
                            $values[] = $pdo->quote($value);
                        }
                    }
                    $value_list = implode(', ', $values);
                    fwrite($file, "INSERT INTO `$table` ($column_list) VALUES ($value_list);\n");
                }
                fwrite($file, "\n");
            }
        }
        
        fwrite($file, "COMMIT;\n");
        fclose($file);
        
        $file_size = filesize($output_file);
        echo "\n✅ Database exported successfully using PHP!\n";
        echo "File: " . basename($output_file) . "\n";
        echo "Size: " . number_format($file_size / 1024, 2) . " KB\n";
        echo "Tables exported: " . count($tables) . "\n";
        echo "\n";
        echo "File location: " . $output_file . "\n";
        
    } catch (Exception $e) {
        echo "❌ Error: " . $e->getMessage() . "\n";
        if (isset($file) && $file) {
            fclose($file);
        }
    }
}

echo "\n========================================\n";


